apiVersion: certificates.k8s.io/v1
kind: CertificateSigningRequest
metadata:
  name: ttt-csr
spec:
  groups:
  - system:authenticated
  request: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURSBSRVFVRVNULS0tLS0KTUlJQ1V6Q0NBVHNDQVFBd0RqRU1NQW9HQTFVRUF3d0RkSFIwTUlJQklqQU5CZ2txaGtpRzl3MEJBUUVGQUFPQwpBUThBTUlJQkNnS0NBUUVBdU1GajM5a2dlSHZObG0vdSt6YTBmKy93MnFwRU5QL0lyUWVxYzloaDV3UGM3djVBCngwUTJrZW5kTnJ4K0dnQTA4bGYrNEwzTVZOam5mcGU4cVFaUTNvNXdVT3V1Skpya0R3VzJJL1dNd28xTHBoZWEKQyt1bzB0OWl5ZDZhSnd0S25MbHRFcVAzbUJPMC9ncmw5cldlcXRpMkU3N0hrVzFhYzlaaTBWZUVVZStEdlFFYQpEdGhIR2dyOGEwdm1nOHFITDQ5QkEwNkhkQ1NHaGljczgvQnNJc3p1eWorTmxISm1rdkJVeDczUHlmcjBQVFNDCnRTS0tWbzcrajdscEdLOTU2ekFBcHhiZXl5ZGFwdE1xdDhFeFh3Z1ZQSThWcVBlekt2ZXdBdTZSNGtvcUdxd2sKKzBrZ2dycUhzZGNYd3l6ZXYyTVBETm1IMW1icCt0RURHQWFwS1FJREFRQUJvQUF3RFFZSktvWklodmNOQVFFTApCUUFEZ2dFQkFGeGRvYWR1cHp6NmZhR0M1Y2xuKytOUThXc1pNd2lsSUUrUjIreXo5WC9YNGhaemVPdDgwM0w1CjhTUXVUY1lrZlgxbG9ITnZ6Uktsc1Q5aDhiREo5dHNoVWl3Nlh0UVR3SVdoUDdOV25KTk54NVowVXlyRzFXVXQKZ21kVFYxZkk0REJoam52T2tQNmhVYlU0KzNjblRoRjQvMnBNUE80RE5CRlVHV3RXQXM1ekVQQk1UWk92T0I0ZApWTE5hVmd0cW1BMGhtSDhQbHBzOFF5VTQ2dE4rRVZ6NkM4amFIeGNIQnYzczVSVlZ0TTAxWElLdWsvc2hTcFdKCnh0OU14Z3VPb0ZaeThxekh3aDlOS1N3dWp2bTBsczNKNkNVM3U5Y0FwT0d5UGFMWUNFQ1FaZWpPUmExRFpnb0kKK2x1a0M0L0NVVmo3TEhIbUtXMkEzQ05jNUI5QTRqcz0KLS0tLS1FTkQgQ0VSVElGSUNBVEUgUkVRVUVTVC0tLS0tCg==
  signerName: kubernetes.io/kube-apiserver-client
  usages:
  - digital signature
  - key encipherment
  - client auth
