apiVersion: certificates.k8s.io/v1
kind: CertificateSigningRequest
metadata:
  name: tit-csr
spec:
  groups:
  - system:authenticated
  request: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURSBSRVFVRVNULS0tLS0KTUlJQ1V6Q0NBVHNDQVFBd0RqRU1NQW9HQTFVRUF3d0RkR2wwTUlJQklqQU5CZ2txaGtpRzl3MEJBUUVGQUFPQwpBUThBTUlJQkNnS0NBUUVBNERFWGJPWkZ2SzFQdGhBZVcrSk16ZVBpSVdxYnNYbjRkZjRWeG9WRzdlQWpSNCtVCkhxSEZHL0VlR1ZPbzNnODJvU010U3JxbjJYeVl4Zk1RV2JIRmhGeFVQNldYdFpmRXE3blRPVjZ5ZlNLeDhqb0cKU1hKMS9WeUU4UzRiVGkxZ3NmL0RSaUdQcmtvLzF4Tm1aM3hJaVl3SjNSRFJVRVhzZncvOEwwUkxBLzZkM2pBTwpTR0RKeFNadkpVVzlIMTB6UXpGc1dZS09NSUNKeFJ4L3MyYkFLdzVtbWFCN2VtRjlYdERQaUZnRXNqVDhVSXJpCjhpUHNQZHhIdUdpUTgxaUxkOHNidHVIYXh6SVF6MlE4RTFrVnBxd1gyVWRWVG0wcExDSjdSK2FjcWl4ZjczdVcKWlRPaFZLSUMxUHpXWGFKY2xldlIwQUxEREw1bTgrTFFHL2U2endJREFRQUJvQUF3RFFZSktvWklodmNOQVFFTApCUUFEZ2dFQkFMUVFTUmRYL3NKT3MwZVBGaWJ0MjZpTHluWmR4M3piVVUxUmZibjFIM05OVnhBclBYRGE0RUU1CkYxQUV1aXBCT2RSMUpSTGlWMFI3L09zNG1CaWVBc0F1WmVUdjFZeDVWQ2JpdHpzcGQwVVF6UG1wZTdwTlVmN0MKUDY1c0htM2pFY0RVd01KWFM5a01jZnRGd0lmSkdwMnlRdTV3NUVVRUdMcFo1OXN3a2ZGQXNMbyttMm5TVm0reQorUGQwQmNqN2E5VVlRd1BEVTBGY3FKYTc1ODlqN2g5RnJXRDBBRDcyY01La1FhVlhyYTZoS1N3a2NXSWxDeTdYCjFyb2Jzd29EK2NMeXZuRjVzejM2SkpscnEyRjVHcGt2MlRMams1T1J6MUhXQVo0VEdUb2lTeUhKZFBFOEdGOWkKK1FyYWt6N2gyZTJKVFU1ZVgxN041VGE1blNjdm5QWT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUgUkVRVUVTVC0tLS0tCg==
  signerName: kubernetes.io/kube-apiserver-client
  usages:
  - digital signature
  - key encipherment
  - client auth
