apiVersion: v1
items:
- apiVersion: rbac.authorization.k8s.io/v1
  kind: RoleBinding
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"rbac.authorization.k8s.io/v1","kind":"RoleBinding","metadata":{"annotations":{},"name":"full-access-binding","namespace":"test-ns"},"roleRef":{"apiGroup":"rbac.authorization.k8s.io","kind":"Role","name":"full-access-role"},"subjects":[{"apiGroup":"rbac.authorization.k8s.io","kind":"User","name":"tster2"}]}
    creationTimestamp: "2024-11-15T10:07:18Z"
    name: longhorn-read-role-binding
    namespace: longhorn-system
    resourceVersion: "20427"
    uid: 1f3b1676-778e-4f9d-a3a8-ca9756d09e58
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: Role
    name: longhorn-read-role
  subjects:
  - apiGroup: rbac.authorization.k8s.io
    kind: User
    name: tster2
kind: List
metadata:
  resourceVersion: ""
