kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: test-ns
  name: full-access-role
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["get","list","watch","create","update","patch","delete"]
