apiVersion: certificates.k8s.io/v1
kind: CertificateSigningRequest
metadata:
  name: john-csr
spec:
  groups:
  - system:authenticated
  request: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURSBSRVFVRVNULS0tLS0KTUlJQ1ZEQ0NBVHdDQVFBd0R6RU5NQXNHQTFVRUF3d0VhbTlvYmpDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRApnZ0VQQURDQ0FRb0NnZ0VCQU5KZ3hqclViS2RsNERLR1F2dzFYQWMzQjRqY2p1eTBlY2xRSWpRMGxxN1lCYVAvCnFRd25xY1dGZjhZbGd1ZWFsRW04TzNzZGxRUFdqYU0rOWRKOWh5MDhBQnRjQksvNTM5OEc5U2dCbm1ZZzl6MGwKR1h6MHNvbXlTSzdZVS9jV2oydjhEK2JWcFRZelNWVnRNU0Z4ejFWeFVaRmVmZjREUkRnVmJCVzE3Ny8wRyt5MApnOXkxVExtbDAvVlRsS0VrakZ5alZpbFYwdDZ1c1ljTk8vY0E1Y2w0elB2R0d1OFF1MUh1R0d1ZHZZeUwwS0hwCm14QmJYdjJvOXpwMXFTQkM3WWw1SCs5S3pMNTlhLzBoNERXbm9YbjhydVRMcXI2ZHBmbVQ1WnFCTXZJY0lBa3kKREw1KzFXL2lwSS9MZUx5ZFpobjNRdnpBV3V4NjRjSUpiR3VJaEpzQ0F3RUFBYUFBTUEwR0NTcUdTSWIzRFFFQgpDd1VBQTRJQkFRQWJKVHBzUmk1Q0ovazNGazNuOFJQSzRiQVMvcFdacmNydGJrNno2QzFpNkhDOVgxR0F1RWhxClA5Wk04TFpOVDJzQk9uc3lXajgwempPanI1aFJ3VmRRRnZuTWtmT01FQStRd3NEQzEvRy95ejhkUGM5VkhsTGgKZUtCNUJKbWkvM3I3RGxHR1dHc0F3NFB5QUdjTTZoYjVmV28xR25PTk54OHF3WENDcXc5Y1dValFkN2V5eTk5dAp1UWNGT2F2UzQwN2hMUE5jcGlobldwY1Q4U2gweTR2MXRWc2xBV1RnbE8rc2EwY3Q3azlQRDNCZ1FJNUtyWitTCjcxNld1U2MrK1RiYzNPaG4vOTdaMEdCenVYL1NJYWFpcUpMNTJNeWFidXM4T3M5Y1A0bkpXUytwMkhNYzNRVUsKWkFFTU5YNkJWQTlHQ2VsTTZWczQ4bkNCV3NGM2NhelQKLS0tLS1FTkQgQ0VSVElGSUNBVEUgUkVRVUVTVC0tLS0tCg==
  signerName: kubernetes.io/kube-apiserver-client
  usages:
  - digital signature
  - key encipherment
  - client auth
