kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: longhorn-system-full-access-role-binding
  namespace: longhorn-system
subjects:
- kind: User
  name: john
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: longhorn-system-full-access-role
  apiGroup: rbac.authorization.k8s.io
